app/users/models.py
from uuid import uuid4

from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash, check_password_hash
from flask_user import UserMixin
from sqlalchemy.dialects.postgresql import UUID

from app import login_manager, db


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)

    domains = db.relationship('DomainData', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError("The password is not a readable attribute.")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    def confirm(self, token):

        serializer = Serializer(current_app.config["SECRET_KEY"])

        try:
            data = serializer.loads(token)
        except Exception as exception:
            print(exception)
            return False

        if data.get("confirm") == self.id:
            self.confirmed = True
            db.session.add(self)
            db.session.commit()
            return True
        else:
            return False

    def __repr__(self):
        return '<User %r>' % (self.username)

app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo

from app.users.models import User


class LoginForm(FlaskForm):

    email = StringField('Email Address', validators=[DataRequired(), Length(1, 64), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember_me = BooleanField("Remember me")
    submit = SubmitField("Log in")


class RegistrationForm(FlaskForm):

    email = StringField("Email", validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField("Username", validators=[DataRequired(), Length(1, 64), Regexp("^[A-Za-z][A-Za-z0-9_.]*$",
                                                                                     0,
                                                                                     "Usernames must only have letters, \
                                                                                      numbers, dots or underscores.")])

    password = PasswordField("Password", validators=[DataRequired(), EqualTo("password_two", message="Passwords must match.")])
    password_two = PasswordField("Confirm password", validators=[DataRequired()])

    submit = SubmitField("Register")

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("Email already registered.")

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError("Username already in use.")


class UpdatePasswordForm(FlaskForm):

    old_password = PasswordField("Old Password", validators=[DataRequired()])
    new_password = PasswordField("New Password", validators=[DataRequired(), EqualTo("new_password_two", message="Passwords must match.")])
    new_password_two = PasswordField("Confirm new password", validators=[DataRequired()])

    submit = SubmitField("Update")

app/users/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, login_user, logout_user, current_user

from app import db
from app.users.forms import LoginForm, RegistrationForm, UpdatePasswordForm
from app.users.models import User
from app.users.utils import delete_domain, delete_user_account
from app.prospector.models import DomainScores, PageScores, DomainData
from app.prospector.forms import DomainScoresForm, PageScoresForm
from app.prospector.utils import (create_default_domain_scores, create_default_page_scores, load_domain_scores_form_to_model,
                                  load_domain_scores_model_to_form, load_page_scores_form_to_model, load_page_scores_model_to_form)


users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/register', methods=["GET", "POST"])
def register():

    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():

        user = User(email=registration_form.email.data,
                    username=registration_form.username.data,
                    password=registration_form.password.data)

        db.session.add(user)
        db.session.commit()

        default_domain_scores = create_default_domain_scores(owner=user.id)
        default_page_scores = create_default_page_scores(owner=user.id)

        db.session.add(default_domain_scores)
        db.session.add(default_page_scores)
        db.session.commit()

        flash("Your account has been created. Please log in.")

        return redirect(url_for("users.login"))

    else:
        return render_template("users/register.html", form=registration_form)


@users_blueprint.route('/login', methods=["GET", "POST"])
def login():

    login_form = LoginForm()

    if login_form.validate_on_submit():

        user = User.query.filter_by(email=login_form.email.data).first()

        if user is not None and user.verify_password(login_form.password.data):
            login_user(user, login_form.remember_me.data)
            return redirect(request.args.get("next") or url_for("prospector.index"))

        else:
            flash("Invalid username or password")

    return render_template("users/login.html", form=login_form)


@users_blueprint.route('/logout')
def logout():
    logout_user()
    flash("You have been logged out.")
    return redirect(url_for("prospector.index"))


@users_blueprint.route('/profile/<username>', methods=["GET", "POST"])
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    return render_template("users/profile.html", user=user)


@users_blueprint.route('/domain_scores/<username>', methods=["GET", "POST"])
@login_required
def edit_domain_scores(username):

    user = User.query.filter_by(username=username).first()

    domain_scores_model = DomainScores.query.filter_by(owner=user.id).first()
    domain_scores_form = DomainScoresForm()

    if domain_scores_form.validate_on_submit():

        domain_scores_model = load_domain_scores_form_to_model(domain_scores_model, domain_scores_form)

        db.session.add(domain_scores_model)
        db.session.commit()
        flash("Your domain scores have been updated.")
        return redirect(url_for("users.edit_domain_scores", username=user.username))

    domain_scores_form = load_domain_scores_model_to_form(domain_scores_model, domain_scores_form)

    return render_template("users/edit_domain_scores.html", user=user, domain_scores_form=domain_scores_form)


@users_blueprint.route('/page_scores/<username>', methods=["GET", "POST"])
@login_required
def edit_page_scores(username):

    user = User.query.filter_by(username=username).first()

    page_scores = PageScores.query.filter_by(owner=user.id).first()
    page_scores_form = PageScoresForm()

    if page_scores_form.validate_on_submit():

        page_scores = load_page_scores_form_to_model(page_scores, page_scores_form)

        db.session.add(page_scores)
        db.session.commit()
        flash("Your page scores have been updated.")
        return redirect(url_for("users.edit_page_scores", username=user.username))

    page_scores_form = load_page_scores_model_to_form(page_scores, page_scores_form)

    return render_template("users/edit_page_scores.html", user=user, page_scores_form=page_scores_form)


@users_blueprint.route('/delete_sites/<username>')
@login_required
def delete_sites(username):

    user = User.query.filter_by(username=username).first()

    if user is not None:
        sites = DomainData.query.filter_by(owner=user.id)
    else:
        sites = DomainData.query.filter_by(owner=None)

    return render_template("users/delete_sites.html", user=user, sites=sites)


@users_blueprint.route('/delete_site/<site_id>')
@login_required
def delete_site(site_id):

    user = current_user

    domain_to_delete = DomainData.query.get(site_id)

    if domain_to_delete and domain_to_delete.owner == user.id:
        delete_domain(domain_to_delete)

        return redirect(url_for("users.delete_sites", username=user.username))

    else:
        return redirect(url_for("users.delete_sites", username=user.username))


@users_blueprint.route('/update-password/<username>', methods=["GET", "POST"])
@login_required
def update_password(username):

    user = current_user

    update_password_form = UpdatePasswordForm()

    if update_password_form.validate_on_submit():

        user.password = update_password_form.new_password.data

        db.session.add(user)
        db.session.commit()

        flash("Your password has been updated.")

        return redirect(url_for("users.profile", username=username))

    else:
        return render_template("users/update_password.html", user=user, form=update_password_form)


@users_blueprint.route('/delete-account/<username>')
@login_required
def delete_account(username):

    user = User.query.filter_by(username=username).first()

    logout_user()
    delete_user_account(user)
    db.session.commit()

    return redirect(url_for("prospector.index"))

app/templates/users/delete_sites.html
{% extends "base.html" %}

{% block page_content %}

    {% if sites.all() %}

        {% for site in sites %}

            <a class="sitebtn {{ site.level }}" onclick="user_confirmation('{{ url_for('users.delete_site', site_id = site.id) }}')" href="#">
                {{site.ranking}}% {{site.domain_url}}
                <p style="float:right; display:inline; padding:0;">X</p>
            </a>
            <br>

        {% endfor %}

    {% else %}

        <div class="no-scrapes">

            <p style="text-align:center;">There are no scraped sites to delete.</p>
            <a href="/">Scrape a site.</a>

        </div>

    {% endif %}

    <script type="text/javascript">

        function user_confirmation(url) {

            if (confirm("Are you sure you want to delete this site?") == true) {
                location.href = url;
            }

        }

    </script>

{% endblock %}

app/templates/users/edit_domain_scores.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}

    <h2>Domain scores</h2>

    {{ wtf.quick_form(domain_scores_form) }}

{% endblock %}

app/templates/users/edit_page_scores.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}

    <h2>Page scores</h2>

    {{ wtf.quick_form(page_scores_form) }}

{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

    <div class="page-header">
        <h2>Log in</h2>
    </div>


    {{ wtf.quick_form(form) }}

    <br>

    <p>
        New user? <a href="{{ url_for('users.register') }}">Click here to register.</a>
    </p>


{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

    <div class="page-header">
        <h2>Hello {{ user.username }}</h2>
    </div>

    <h3><a href="{{ url_for('users.edit_domain_scores', username = current_user.username) }}">Update your domain scores</a></h3>

    <h3><a href="{{ url_for('users.edit_page_scores', username = current_user.username) }}">Update your page scores</a></h3>

    <h3><a href="{{ url_for('users.delete_sites', username = current_user.username) }}">Delete your scraped websites</a></h3>

    <h3><a href="{{ url_for('users.update_password', username = current_user.username) }}">Update your password</a></h3>

    <h3><a onclick="user_confirmation('{{ url_for('users.delete_account', username = current_user.username) }}')">Delete your account</a></h3>

    <br>

    <h3><a href="{{ url_for('users.logout') }}">Log out</a></h3>

    <script type="text/javascript">

        function user_confirmation(url) {

            if (confirm("Are you sure you want to delete your account? This cannot be undone.") == true) {
                location.href = url;
            }

        }

    </script>

{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

    <div class="page-header">
        <h2>Register</h2>
    </div>


    {{ wtf.quick_form(form) }}

    <br>

    <p>
        Already an existing user? <a href="{{ url_for('users.login') }}">Click here to log in.</a>
    </p>


{% endblock %}

app/templates/users/update_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}


    <div class="page-header">
        <h2>Update password</h2>
    </div>

    {{ wtf.quick_form(form) }}

{% endblock %}