app/prospector/views.py
from flask import current_app, Blueprint, render_template, redirect, url_for
from flask_login import current_user

from app.prospector.models import DomainData, PageData, db
from app.prospector.forms import UrlEntry
from app.prospector import crawler
from app.prospector import ranker
from app.prospector.utils import format_url, get_or_create_domain_data


prospector_blueprint = Blueprint('prospector', __name__)

# SITES_PER_PAGE = current_app.config["SITES_PER_PAGE"]
SITES_PER_PAGE = 10


@prospector_blueprint.route('/', methods=['GET', 'POST'])
def index():

    user = None
    if current_user.is_authenticated:
        user = current_user

    form = UrlEntry()

    if form.validate_on_submit():

        url_to_prospect = format_url(form.url.data)

        domain_data = get_or_create_domain_data(url_to_prospect, user)
        domain_data = crawler.scrape_domain_data(domain_data)

        pages_to_scrape = crawler.spider_site(domain_data.domain_url)
        pages_data = [crawler.scrape_page_data(page_to_scrape, domain_data) for page_to_scrape in pages_to_scrape]

        domain_data.ranking = ranker.rank_site(domain_data)
        domain_data.level = ranker.domain_level_calculator(domain_data.ranking)

        db.session.add(domain_data)
        db.session.add_all(pages_data)
        db.session.commit()

        return redirect(url_for('prospector.siteinspect', site_name=domain_data.site_name))

    return render_template("index.html", form=form)


@prospector_blueprint.route('/sites')
def sitelist():

    user = None
    if current_user.is_authenticated:
        user = current_user

    if user is not None:
        sites = DomainData.query.filter_by(owner=user.id).limit(SITES_PER_PAGE)
    else:
        sites = DomainData.query.filter_by(owner=None).limit(SITES_PER_PAGE)

    return render_template("sitelist.html", sites=sites)


@prospector_blueprint.route('/site/<site_name>')
@prospector_blueprint.route('/site/<site_name>/<int:page>')
def siteinspect(site_name, page=1):

    if site_name is None:
        return redirect(url_for('index'))

    site = db.session.query(DomainData).filter_by(site_name=site_name).first()

    # currentPages = PageData.query.filter_by(site_id=site.id).paginate(page, 1, False)
    currentPages = db.paginate(PageData.query.filter_by(site_id=site.id))

    return render_template("siteinspect.html", site=site, currentPages=currentPages)


@prospector_blueprint.route('/site/<site_name>/all')
def site_inspect_all_pages(site_name):

    if site_name is None:
        return redirect(url_for('index'))

    site = db.session.query(DomainData).filter_by(site_name=site_name).first()

    all_pages = PageData.query.filter_by(site_id=site.id).all()

    return render_template("site_inspect_all_pages.html", site=site, all_pages=all_pages)

app/users/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, login_user, logout_user, current_user

from app import db
from app.users.forms import LoginForm, RegistrationForm, UpdatePasswordForm
from app.users.models import User
from app.users.utils import delete_domain, delete_user_account
from app.prospector.models import DomainScores, PageScores, DomainData
from app.prospector.forms import DomainScoresForm, PageScoresForm
from app.prospector.utils import (create_default_domain_scores, create_default_page_scores, load_domain_scores_form_to_model,
                                  load_domain_scores_model_to_form, load_page_scores_form_to_model, load_page_scores_model_to_form)


users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/register', methods=["GET", "POST"])
def register():

    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():

        user = User(email=registration_form.email.data,
                    username=registration_form.username.data,
                    password=registration_form.password.data)

        db.session.add(user)
        db.session.commit()

        default_domain_scores = create_default_domain_scores(owner=user.id)
        default_page_scores = create_default_page_scores(owner=user.id)

        db.session.add(default_domain_scores)
        db.session.add(default_page_scores)
        db.session.commit()

        flash("Your account has been created. Please log in.")

        return redirect(url_for("users.login"))

    else:
        return render_template("users/register.html", form=registration_form)


@users_blueprint.route('/login', methods=["GET", "POST"])
def login():

    login_form = LoginForm()

    if login_form.validate_on_submit():

        user = User.query.filter_by(email=login_form.email.data).first()

        if user is not None and user.verify_password(login_form.password.data):
            login_user(user, login_form.remember_me.data)
            return redirect(request.args.get("next") or url_for("prospector.index"))

        else:
            flash("Invalid username or password")

    return render_template("users/login.html", form=login_form)


@users_blueprint.route('/logout')
def logout():
    logout_user()
    flash("You have been logged out.")
    return redirect(url_for("prospector.index"))


@users_blueprint.route('/profile/<username>', methods=["GET", "POST"])
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first()
    return render_template("users/profile.html", user=user)


@users_blueprint.route('/domain_scores/<username>', methods=["GET", "POST"])
@login_required
def edit_domain_scores(username):

    user = User.query.filter_by(username=username).first()

    domain_scores_model = DomainScores.query.filter_by(owner=user.id).first()
    domain_scores_form = DomainScoresForm()

    if domain_scores_form.validate_on_submit():

        domain_scores_model = load_domain_scores_form_to_model(domain_scores_model, domain_scores_form)

        db.session.add(domain_scores_model)
        db.session.commit()
        flash("Your domain scores have been updated.")
        return redirect(url_for("users.edit_domain_scores", username=user.username))

    domain_scores_form = load_domain_scores_model_to_form(domain_scores_model, domain_scores_form)

    return render_template("users/edit_domain_scores.html", user=user, domain_scores_form=domain_scores_form)


@users_blueprint.route('/page_scores/<username>', methods=["GET", "POST"])
@login_required
def edit_page_scores(username):

    user = User.query.filter_by(username=username).first()

    page_scores = PageScores.query.filter_by(owner=user.id).first()
    page_scores_form = PageScoresForm()

    if page_scores_form.validate_on_submit():

        page_scores = load_page_scores_form_to_model(page_scores, page_scores_form)

        db.session.add(page_scores)
        db.session.commit()
        flash("Your page scores have been updated.")
        return redirect(url_for("users.edit_page_scores", username=user.username))

    page_scores_form = load_page_scores_model_to_form(page_scores, page_scores_form)

    return render_template("users/edit_page_scores.html", user=user, page_scores_form=page_scores_form)


@users_blueprint.route('/delete_sites/<username>')
@login_required
def delete_sites(username):

    user = User.query.filter_by(username=username).first()

    if user is not None:
        sites = DomainData.query.filter_by(owner=user.id)
    else:
        sites = DomainData.query.filter_by(owner=None)

    return render_template("users/delete_sites.html", user=user, sites=sites)


@users_blueprint.route('/delete_site/<site_id>')
@login_required
def delete_site(site_id):

    user = current_user

    domain_to_delete = DomainData.query.get(site_id)

    if domain_to_delete and domain_to_delete.owner == user.id:
        delete_domain(domain_to_delete)

        return redirect(url_for("users.delete_sites", username=user.username))

    else:
        return redirect(url_for("users.delete_sites", username=user.username))


@users_blueprint.route('/update-password/<username>', methods=["GET", "POST"])
@login_required
def update_password(username):

    user = current_user

    update_password_form = UpdatePasswordForm()

    if update_password_form.validate_on_submit():

        user.password = update_password_form.new_password.data

        db.session.add(user)
        db.session.commit()

        flash("Your password has been updated.")

        return redirect(url_for("users.profile", username=username))

    else:
        return render_template("users/update_password.html", user=user, form=update_password_form)


@users_blueprint.route('/delete-account/<username>')
@login_required
def delete_account(username):

    user = User.query.filter_by(username=username).first()

    logout_user()
    delete_user_account(user)
    db.session.commit()

    return redirect(url_for("prospector.index"))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
	Prospector
{% endblock %}

{% block head %}

	{{ super() }}
	<link href="/static/css/site.css" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>

{% endblock %}

{% block content %}

	<header>
		<h1><a href="{{ url_for('prospector.index') }}">Prospector</a></h1>
	</header>


	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">

				{% with messages = get_flashed_messages(with_categories=true) %}
				  <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
				  {% if messages %}
				    {% for category, message in messages %}
				      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
				      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				      <!-- <strong>Title</strong> --> {{ message }}
				      </div>
				    {% endfor %}
				  {% endif %}
				{% endwith %}


				{% block page_content %}{% endblock %}
			</div>
		</div>
	</div>

{% endblock %}

app/templates/index.html
{% extends "bootstrap/base.html" %}

{% block title %}
    Prospector
{% endblock %}

{% block head %}

    {{ super() }}
    <link href="/static/css/site.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>

{% endblock %}

{% block content %}

    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <div class="index">

                <h1>Prospector</h1>

                <form class="form form-horizontal" method="POST" role="form">

                    {{ form.csrf_token }}
                    {{ form.url(size=150, class="form-control", placeholder="http://www.website.co.uk") }}

                    <input type="submit" value="Prospect" class="btn btn-red">

                </form>

                <a href="{{ url_for('prospector.sitelist') }}">View previously analysed sites</a>

                {% for error in form.errors.url %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}

                {% with messages = get_flashed_messages(with_categories=true) %}
                  <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
                  {% if messages %}
                    {% for category, message in messages %}
                      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <!-- <strong>Title</strong> --> {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
                {% endwith %}

            </div>

            <div class="index-auth footer navbar-fixed-bottom">

                <div class="container text-center">

                    {% if current_user.is_authenticated %}
                        <p>Currently logged in as <a href="{{ url_for('users.profile', username = current_user.username) }}">{{ current_user.username }}</a></p>
                    {% else %}
                        <p>
                            <a href="{{ url_for('users.login') }}">Log in</a> - <a href="{{ url_for('users.register') }}">Register</a>
                        </p>
                    {% endif %}

                </div>

            </div>

        </div>
      </div>
    </div>

{% endblock %}

app/templates/site-inspect-all-pages.html
{% extends "base.html" %}

{% block page_content %}

{% endblock %}

app/templates/site_inspect_all_pages.html
{% extends "base.html" %}

{% block page_content %}

    <a class="sitebtn {{ site.level }}" href="{{ url_for('prospector.sitelist') }}"> < {{ site.ranking }}% {{ site.domain_url }}</a>

    <div class="all-pages">

        {% for page in all_pages %}
            <a href="{{ url_for('prospector.siteinspect', site_name=site.site_name, page=loop.index) }}">
                {{ page.page_url }}
            </a>
        {% endfor %}

    </div>

{% endblock %}

app/templates/siteinspect.html
{% extends "base.html" %}

{% block page_content %}

	<a class="sitebtn {{ site.level }}" href="{{ url_for('prospector.sitelist') }}"> < {{ site.ranking }}% {{ site.domain_url }}</a>

	<div id="domain">

		<table>
			<tr>
				<th>bing anayltics</th>
				{% if site.bing_analytics %}
					<td>present</td>
				{% else %}
					<td class="gray">not present</td>
				{% endif %}
			</tr>

			<tr>
				<th>google anayltics</th>
				{% if site.google_analytics %}
					<td>present</td>
				{% else %}
					<td class="gray">not present</td>
				{% endif %}
			</tr>

			<tr>
				<th>robots.txt</th>
				{% if site.robots %}
					<td>present</td>
				{% else %}
					<td class="gray">not present</td>
				{% endif %}
			</tr>

			<tr>
				<th>sitemap.xml</th>
				{% if site.sitemap %}
					<td>present</td>
				{% else %}
					<td class="gray">not present</td>
				{% endif %}
			</tr>

		</table>
	</div>

	<div id="page">

		{% for currentPage in currentPages.items %}

		<a href="{{ currentPage.page_url }}" target="_blank">
			{{ currentPage.page_url }}
		</a>

		<table>

			<tr>
				<th>title</th>
				{% if currentPage.title_text %}
					<td>{{ currentPage.title_text }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>h1 tags</th>
				{% if currentPage.h1_tags %}
					<td>
					{% for h1_tag in currentPage.h1_tags %}
						{{ h1_tag }} </br>
					{% endfor %}
					</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>h2 tags</th>
				{% if currentPage.h2_tags %}
					<td>
					{% for h2_tag in currentPage.h2_tags %}
						{{ h2_tag }} </br>
					{% endfor %}
					</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>h3 tags</th>
				{% if currentPage.h3_tags %}
					<td>
					{% for h3_tag in currentPage.h3_tags %}
						{{ h3_tag }} </br>
					{% endfor %}
					</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>alt tags</th>
				{% if currentPage.alt_tags %}
					<td>
					{% for alt_tag in currentPage.alt_tags %}
						{{ alt_tag }} </br>
					{% endfor %}
					</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>meta description tags</th>
				{% if currentPage.meta_descriptions %}
					<td>
					{% for meta_description in currentPage.meta_descriptions %}
						{{ meta_description }} </br>
					{% endfor %}
					</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>viewstate</th>
				{% if currentPage.view_state %}
					<td>{{ currentPage.view_state }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>pagination</th>
				{% if currentPage.pagination %}
					<td>{{ currentPage.pagination }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>iframe</th>
				{% if currentPage.iframe_content == True %}
					<td>{{ currentPage.iframe_content }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>flash</th>
				{% if currentPage.flash_attribute == True %}
					<td>{{ currentPage.flash_attribute }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>no index no follow</th>
				{% if currentPage.no_index_no_follow_attribute == True %}
					<td>{{ currentPage.no_index_no_follow_attribute }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>schema tag</th>
				{% if currentPage.schema_tags %}
					<td>present</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>blog location</th>
				{% if currentPage.blog_locations %}
					<td>
					{% for blog_location in currentPage.blog_locations %}
						{{ blog_location }} </br>
					{% endfor %}
					</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>internal links</th>
				{% if currentPage.number_of_internal_links %}
					<td>{{ currentPage.number_of_internal_links }}</td>
				{% else %}
					<td class="gray">not present</td
				{% endif %}
			</tr>

			<tr>
				<th>url character length</th>
				<td>{{ currentPage.page_url|length }}</td>
			</tr>

			{% endfor %}
		</table>
	</div>

	<nav class="site-inspect">

		<div class="previous">
			<a  {% if not currentPages.has_prev %} style="visibility: hidden;" {% endif %}
				href="{{ url_for('prospector.siteinspect', site_name = site.site_name, page = currentPages.prev_num) }}">
				<< previous page
			</a>
		</div>


		{% if currentPages.has_prev or currentPages.has_next %}

			<div class="all">
				<a href="{{ url_for('prospector.site_inspect_all_pages', site_name = site.site_name) }}">
					all pages
				</a>
			</div>

		{% endif %}


		<div class="next">
			<a  {% if not currentPages.has_next %} style="visibility: hidden;" {% endif %}
				href="{{ url_for('prospector.siteinspect', site_name = site.site_name, page = currentPages.next_num) }}">
				next page >>
			</a>
		</div>

	</nav>

{% endblock %}

app/templates/sitelist.html
{% extends "base.html" %}

{% block page_content %}

        {% if sites.all() %}

    		{% for site in sites %}

    			<a class="sitebtn {{ site.level }}" href="{{ url_for('prospector.siteinspect', site_name = site.site_name) }}">
                    {{site.ranking}}% {{site.domain_url}} >
                </a>

                <br>

    		{% endfor %}

        {% else %}

            <div class="no-scrapes">

                <p style="text-align:center;">No sites have been scraped yet.</p>
                <a href="/">Scrape a site.</a>

            </div>

        {% endif %}

{% endblock %}